task: trying new strategy for version

diff --git a/.github/workflows/test-and-deploy.yml b/.github/workflows/test-and-deploy.yml
--- a/.github/workflows/test-and-deploy.yml
+++ b/.github/workflows/test-and-deploy.yml
@@ -26,6 +26,24 @@ jobs:
     
     - run: npm test
       if: runner.os != 'Linux'
+
+    - name: get release version
+      if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
+      id: release_version
+      run: |
+        TAGGED_VERSION="${GITHUB_REF/refs\/tags\/v/}"
+        if [[ ! "${TAGGED_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
+          echo "Invalid version tag '${TAGGED_VERSION}'"
+          exit 1
+        fi
+        
+        echo "EXT_VERSION=${TAGGED_VERSION}" >> $GITHUB_ENV
+        
+    - name: stamp version
+      if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
+      run: |
+        cat package.json | jq --arg VER "${{ env.EXT_VERSION }}" '.version=$VER' > /tmp/package.json 
+        cp /tmp/package.json ./package.json
     
     - name: Publish
       if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
